# Generated by Django 6.0.6 on 2026-07-04 14:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pickup_address', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('XAF', 'Central African CFA Franc')], default='XAF', max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.CharField(choices=[('WASH_FOLD', 'Wash & Fold'), ('WASH_IRON', 'Wash & Iron'), ('DRY_CLEAN', 'Dry Clean'), ('IRON_ONLY', 'Iron Only')], max_length=20)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('READY', 'Ready'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name_plural': 'order status histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickupDeliverySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time_slot', models.CharField(choices=[('MORNING', '8:00 - 11:00'), ('MIDDAY', '11:00 - 14:00'), ('AFTERNOON', '14:00 - 17:00'), ('EVENING', '17:00 - 19:00')], max_length=10)),
                ('pickup_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=12)),
                ('delivery_date', models.DateField()),
                ('delivery_time_slot', models.CharField(choices=[('MORNING', '8:00 - 11:00'), ('MIDDAY', '11:00 - 14:00'), ('AFTERNOON', '14:00 - 17:00'), ('EVENING', '17:00 - 19:00')], max_length=10)),
                ('delivery_status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed')], default='SCHEDULED', max_length=12)),
                ('driver_notes', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='orders.order')),
            ],
            options={
                'ordering': ['pickup_date'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='orders_orde_user_id_02a211_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
    ]
