# Generated by Django 6.0.6 on 2026-07-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, help_text='Optional notes about this item — stains, special handling, etc.'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='label',
            field=models.CharField(blank=True, help_text="Short name for this item, e.g. 'Blue jeans' or 'Winter jacket'.", max_length=100),
        ),
    ]
