# Generated by Django 5.2.16 on 2026-07-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_service_type_lavomatique_lines'),
        ('payments', '0002_alter_payment_gateway_alter_paymentmethod_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_used', to='payments.subscription'),
        ),
    ]
