# Generated by Django 6.0.8 on 2026-08-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='service_type',
            field=models.CharField(choices=[('VESTE', 'Veste (Jacket)'), ('TSHIRT', 'T-Shirt'), ('CHEMISE', 'Chemise (Shirt)'), ('PANTALON', 'Pantalon (Trousers)'), ('PULL', 'Pull (Sweater)'), ('ROBE', 'Robe / Grande Robe / Robe de Soirée'), ('ENSEMBLE', 'Ensemble'), ('DRAPS_COMPLET', 'Draps Complet (Bed Sheet Set)'), ('COUETTE_1P', 'Couette 1 Place'), ('COUETTE_2P', 'Couette 2 Places'), ('COUETTE_3P', 'Couette 3 Places'), ('LAVAGE_ESSORAGE', 'Lavage et Essorage (Wash & Spin)'), ('LAVAGE_SECHAGE', 'Lavage, Essorage et Séchage (Wash & Dry)'), ('REPASSAGE_PLASTIF', 'Repassage et Plastification (Press & Wrap)')], max_length=20),
        ),
    ]
