# Generated by Django 6.0.6 on 2026-07-15 01:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date', 'category'], name='finance_exp_date_8ba413_idx'),
        ),
    ]
