#!/usr/bin/env bash
# Idempotent project scaffolder.
# Run from the project basedir: ./scaffold.sh
# Safe to re-run: mkdir -p never fails on existing dirs,
# and `touch` never truncates a file that already has content.
set -euo pipefail

dirs=(
  "app/(public)/about"
  "app/(public)/pricing"
  "app/(public)/contact"
  "app/(auth)/login"
  "app/(auth)/register"
  "app/(auth)/forgot-password"
  "app/(auth)/reset-password"
  "app/(customer)/dashboard"
  "app/(customer)/book/schedule"
  "app/(customer)/book/review"
  "app/(customer)/book/confirm"
  "app/(customer)/orders/[id]"
  "app/(customer)/chat/[roomId]"
  "app/(customer)/loyalty"
  "app/(customer)/notifications"
  "app/(customer)/settings/preferences"
  "app/(customer)/settings/payments"
  "app/(admin)/admin/orders/[id]"
  "app/(admin)/admin/payments/refunds"
  "app/(admin)/admin/discounts/new"
  "app/(admin)/admin/chat"
  "app/(admin)/admin/customers/[id]"
  "app/(admin)/admin/staff"
  "app/(admin)/admin/analytics"
  "app/api/[...proxy]"
  "components/ui"
  "components/layout"
  "components/auth"
  "components/booking"
  "components/orders"
  "components/payments"
  "components/discounts"
  "components/chat"
  "components/notifications"
  "components/admin"
  "lib/api"
  "lib/stores"
  "types"
  "hooks"
)

files=(
  "app/(public)/page.tsx"
  "app/(public)/about/page.tsx"
  "app/(public)/pricing/page.tsx"
  "app/(public)/contact/page.tsx"
  "app/(auth)/login/page.tsx"
  "app/(auth)/register/page.tsx"
  "app/(auth)/forgot-password/page.tsx"
  "app/(auth)/reset-password/page.tsx"
  "app/(customer)/dashboard/page.tsx"
  "app/(customer)/book/page.tsx"
  "app/(customer)/book/schedule/page.tsx"
  "app/(customer)/book/review/page.tsx"
  "app/(customer)/book/confirm/page.tsx"
  "app/(customer)/orders/page.tsx"
  "app/(customer)/orders/[id]/page.tsx"
  "app/(customer)/chat/page.tsx"
  "app/(customer)/chat/[roomId]/page.tsx"
  "app/(customer)/loyalty/page.tsx"
  "app/(customer)/notifications/page.tsx"
  "app/(customer)/settings/page.tsx"
  "app/(customer)/settings/preferences/page.tsx"
  "app/(customer)/settings/payments/page.tsx"
  "app/(admin)/admin/page.tsx"
  "app/(admin)/admin/orders/page.tsx"
  "app/(admin)/admin/orders/[id]/page.tsx"
  "app/(admin)/admin/payments/page.tsx"
  "app/(admin)/admin/payments/refunds/page.tsx"
  "app/(admin)/admin/discounts/page.tsx"
  "app/(admin)/admin/discounts/new/page.tsx"
  "app/(admin)/admin/chat/page.tsx"
  "app/(admin)/admin/customers/page.tsx"
  "app/(admin)/admin/customers/[id]/page.tsx"
  "app/(admin)/admin/staff/page.tsx"
  "app/(admin)/admin/analytics/page.tsx"
  "app/api/[...proxy]/route.ts"
  "app/layout.tsx"
  "app/not-found.tsx"
  "app/error.tsx"
  "lib/api/auth.ts"
  "lib/api/orders.ts"
  "lib/api/payments.ts"
  "lib/api/discounts.ts"
  "lib/api/chat.ts"
  "lib/api/notifications.ts"
  "lib/stores/auth.store.ts"
  "lib/stores/booking.store.ts"
  "lib/stores/chat.store.ts"
  "lib/socket.ts"
  "lib/utils.ts"
  "lib/constants.ts"
  "types/user.ts"
  "types/order.ts"
  "types/payment.ts"
  "types/discount.ts"
  "types/chat.ts"
  "hooks/useAuth.ts"
  "hooks/useBooking.ts"
  "hooks/useSocket.ts"
  "hooks/useNotifications.ts"
  "middleware.ts"
)

for d in "${dirs[@]}"; do
  mkdir -p -- "$d"
done

for f in "${files[@]}"; do
  mkdir -p -- "$(dirname "$f")"
  [ -e "$f" ] || touch -- "$f"
done

echo "Scaffold complete: ${#dirs[@]} directories ensured, ${#files[@]} files ensured."
