export * from "./client";
export * as authApi from "./auth";
export * as profileApi from "./profile";
export * as ordersApi from "./orders";
export * as scheduleApi from "./schedule";
export * as paymentsApi from "./payments";
export * as discountsApi from "./discounts";
export * as chatApi from "./chat";
export * as notificationsApi from "./notifications";
export * as customersApi from "./customers";
export * as staffApi from "./staff";
export * as financeApi from "./finance";
export * as inventoryApi from "./inventory";
