# Generated by Django 6.0.6 on 2026-07-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Card (Stripe)'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash on Delivery/Pickup'), ('CREDIT', 'Pay Later (Store Credit)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Card (Stripe)'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash on Delivery/Pickup'), ('CREDIT', 'Pay Later (Store Credit)')], max_length=20),
        ),
    ]
