# Generated by Django 5.2.16 on 2026-07-17 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_subscription'),
        ('payments', '0002_alter_payment_gateway_alter_paymentmethod_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.subscription'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_cycle',
            field=models.CharField(choices=[('ONE_TIME', 'One-time (single 30-day period)'), ('MONTHLY', 'Monthly auto-billing')], default='ONE_TIME', max_length=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='external_subscription_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(blank=True, choices=[('STRIPE', 'Card (Stripe)'), ('PAYPAL', 'PayPal'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash on Delivery/Pickup'), ('CREDIT', 'Pay Later (Store Credit)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Card (Stripe)'), ('PAYPAL', 'PayPal'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash on Delivery/Pickup'), ('CREDIT', 'Pay Later (Store Credit)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='gateway',
            field=models.CharField(choices=[('STRIPE', 'Card (Stripe)'), ('PAYPAL', 'PayPal'), ('MTN_MOMO', 'MTN Mobile Money'), ('ORANGE_MONEY', 'Orange Money'), ('CASH', 'Cash on Delivery/Pickup'), ('CREDIT', 'Pay Later (Store Credit)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', False), ('subscription__isnull', True)), models.Q(('order__isnull', True), ('subscription__isnull', False)), _connector='OR'), name='payment_targets_exactly_one_of_order_or_subscription'),
        ),
    ]
