# Generated by Django 6.0.8 on 2026-08-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_subscription_subscription_billing_cycle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='orders_remaining',
        ),
        migrations.AddField(
            model_name='subscription',
            name='kg_remaining',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('ESSENTIEL', 'Pack Essentiel — 10kg / month'), ('CONFORT', 'Pack Confort — 20kg / month'), ('FAMILLE', 'Pack Famille — 30kg / month')], max_length=20),
        ),
    ]
