# Generated by Django 6.0.8 on 2026-08-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rework_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Required for MTN_MOMO/ORANGE_MONEY — the number CamPay will push the collection request to.', max_length=20),
        ),
    ]
