# Generated by Django 6.0.8 on 2026-08-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentmethod_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='display_label',
            field=models.CharField(editable=False, help_text="Computed, e.g. 'MTN •••• 4521' or 'Orange •••• 5249'.", max_length=50),
        ),
    ]
